\doxysection{pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Timeout\+Error Class Reference}
\hypertarget{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1_timeout_error}{}\label{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1_timeout_error}\index{pip.\_vendor.urllib3.exceptions.TimeoutError@{pip.\_vendor.urllib3.exceptions.TimeoutError}}
Inheritance diagram for pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Timeout\+Error\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=4.444445cm]{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1_timeout_error}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb} Raised when a socket timeout error occurs.

Catching this error will catch both :exc:`ReadTimeoutErrors
<ReadTimeoutError>` and :exc:`ConnectTimeoutErrors <ConnectTimeoutError>`.
\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
C\+:/\+Users/kmarty/\+Documents/\+Labo3\+\_\+architecture\+\_\+killian\+\_\+marty/\+Lib/site-\/packages/pip/\+\_\+vendor/urllib3/exceptions.\+py\end{DoxyCompactItemize}
