\doxysection{pip.\+\_\+vendor.\+pep517.\+\_\+in\+\_\+process.\+\_\+\+Dummy\+Exception Class Reference}
\hypertarget{classpip_1_1__vendor_1_1pep517_1_1__in__process_1_1___dummy_exception}{}\label{classpip_1_1__vendor_1_1pep517_1_1__in__process_1_1___dummy_exception}\index{pip.\_vendor.pep517.\_in\_process.\_DummyException@{pip.\_vendor.pep517.\_in\_process.\_DummyException}}
Inheritance diagram for pip.\+\_\+vendor.\+pep517.\+\_\+in\+\_\+process.\+\_\+\+Dummy\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classpip_1_1__vendor_1_1pep517_1_1__in__process_1_1___dummy_exception}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Nothing should ever raise this exception\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
C\+:/\+Users/kmarty/\+Documents/\+Labo3\+\_\+architecture\+\_\+killian\+\_\+marty/\+Lib/site-\/packages/pip/\+\_\+vendor/pep517/\+\_\+in\+\_\+process.\+py\end{DoxyCompactItemize}
