\doxysection{werkzeug.\+routing.\+converters.\+Validation\+Error Class Reference}
\hypertarget{classwerkzeug_1_1routing_1_1converters_1_1_validation_error}{}\label{classwerkzeug_1_1routing_1_1converters_1_1_validation_error}\index{werkzeug.routing.converters.ValidationError@{werkzeug.routing.converters.ValidationError}}
Inheritance diagram for werkzeug.\+routing.\+converters.\+Validation\+Error\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classwerkzeug_1_1routing_1_1converters_1_1_validation_error}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Validation error.  If a rule converter raises this exception the rule
does not match the current URL and the next URL is tried.
\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
C\+:/\+Users/kmarty/\+Documents/\+Labo3\+\_\+architecture\+\_\+killian\+\_\+marty/\+Lib/site-\/packages/werkzeug/routing/converters.\+py\end{DoxyCompactItemize}
