\doxysection{pip.\+\_\+internal.\+exceptions.\+Pip\+Error Class Reference}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1_pip_error}{}\label{classpip_1_1__internal_1_1exceptions_1_1_pip_error}\index{pip.\_internal.exceptions.PipError@{pip.\_internal.exceptions.PipError}}
Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Pip\+Error\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=8.832808cm]{classpip_1_1__internal_1_1exceptions_1_1_pip_error}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Base pip exception\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
C\+:/\+Users/kmarty/\+Documents/\+Labo3\+\_\+architecture\+\_\+killian\+\_\+marty/\+Lib/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
